theme: jekyll-theme-cayman
lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
plugins:
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
relative_links:
  enabled:     true
  collections: false
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
optional_front_matter:
  remove_originals: true